hero1=('Batsman','Bruce wayne')
hero2=('Wonder woman','Diana prince')
new_type=(hero1,hero2)
print(new_type)
print(new_type[0])
print(new_type[0][1])
print(new_type[1][0])
print(new_type[1][1])
print(new_type[1][1][0])